### ISSUE TITLE
Uploading PDF fails

### ISSUE THREAD

**Issue by MandaloreUltimate** [habi/latex-test#1]
Hello, thanks for the helpful repo, I would've never figured out how to work with this Action on my own. However, while following your instructions for this repo fork, I have encountered the problem on 'Upload' stage which fails with this message:

> Run set -e
Initialized empty Git repository in /home/runner/work/latex-test/latex-test/deploy/.git/
Switched to a new branch 'gh-pages'
[gh-pages (root-commit) a1fa795] [github actions] deploy
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 main.pdf
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.
##[error]Process completed with exit code 128.

Could you give me an advice on how this issue could be fixed? I don't think I got the idea behind SSH keys and how exactly are they connected to my repo. Is it like we create pdf in GitHub Actions workspace, connect it to our PC via SSH key provided to copy pdf onto it, then push pdf to gh-pages branch? I work with GitHub on Windows and had generated keys in Ubuntu VM (which stays operational during the build), could it be the case? And should I change [this line](https://github.com/habi/latex-test/blob/master/.github/workflows/main.yaml#L41), inserting the link of my repo .git instead?

**Comment by habi** [comment]
I generated the SSH key on Ubuntu, exactly according to what is specified in my README.md.
You *need* to change [line 41 in the YAML file](https://github.com/habi/latex-test/blob/master/.github/workflows/main.yaml#L41) and point it to your repo, otherwise it won't work.

If it works, then you can close the issue, otherwise keep commenting here!

**Comment by habi** [comment]
PS: I've seen that https://MandaloreUltimate.github.io/latex-test/main.pdf is available, so I guess it now works.
I've sent you a PR to change the author name and am closing this issue now.

**Comment by MandaloreUltimate** [comment]
Thanks for the reply, although I've fixed the problem by using [slightly different approach](https://github.com/MandaloreUltimate/latex-test/blob/master/.github/workflows/main.yaml#L39) to connect to repo.
